const chapters = [
    {
      name: "Alcohol and Phenol",
      tests: 5,
      icon: "🍶",
      link: "/tests/Chemistry/alcohol-and-phenol",
    },
    {
      name: "Aldehyde and Ketone",
      tests: 5,
      icon: "⚗️",
      link: "/tests/Chemistry/aldehyde-and-ketone",
    },
    {
      name: "Alkyl Halides",
      tests: 5,
      icon: "🧪",
      link: "/tests/Chemistry/alkyl-halides",
    },
    {
      name: "Atomic Structure",
      tests: 5,
      icon: "⚛️",
      link: "/tests/Chemistry/atomic-structure",
    },
    {
      name: "Carboxylic Acids",
      tests: 5,
      icon: "🧪",
      link: "/tests/Chemistry/carboxylic-acids",
    },
    {
      name: "Chemical Bonding",
      tests: 5,
      icon: "🔗",
      link: "/tests/Chemistry/chemical-bonding",
    },
    {
      name: "Chemical Equilibrium",
      tests: 5,
      icon: "⚖️",
      link: "/tests/Chemistry/chemical-equilibrium",
    },
    {
      name: "Chemistry of Hydrocarbons",
      tests: 5,
      icon: "⛽",
      link: "/tests/Chemistry/chemistry-of-hydrocarbons",
    },
    {
      name: "Electrochemistry",
      tests: 5,
      icon: "🔋",
      link: "/tests/Chemistry/electrochemistry",
    },
    {
      name: "Fundamental Concepts of Chemistry",
      tests: 5,
      icon: "⚗️",
      link: "/tests/Chemistry/fundamental-concepts-of-chemistry",
    },
    {
      name: "Fundamental Principles of Organic Chemistry",
      tests: 5,
      icon: "🧬",
      link: "/tests/Chemistry/fundamental-principles-of-organic-chemistry",
    },
    {
      name: "Gases",
      tests: 5,
      icon: "💨",
      link: "/tests/Chemistry/gases",
    },
    {
      name: "Industrial Chemistry",
      tests: 5,
      icon: "🏭",
      link: "/tests/Chemistry/industrial-chemistry",
    },
    {
      name: "Liquids",
      tests: 5,
      icon: "💧",
      link: "/tests/Chemistry/liquids",
    },
    {
      name: "Macromolecules",
      tests: 5,
      icon: "🧬",
      link: "/tests/Chemistry/macromolecules",
    },
    {
      name: "Reaction Kinetics",
      tests: 5,
      icon: "⏱️",
      link: "/tests/Chemistry/reaction-kinetics",
    },
    {
      name: "s-Block Elements",
      tests: 5,
      icon: "🧪",
      link: "/tests/Chemistry/s-block-elements",
    },
    {
      name: "Solids",
      tests: 5,
      icon: "🧊",
      link: "/tests/Chemistry/solids",
    },
    {
      name: "Thermochemistry",
      tests: 5,
      icon: "🌡️",
      link: "/tests/Chemistry/thermochemistry",
    },
    {
      name: "Transition Elements",
      tests: 5,
      icon: "🔬",
      link: "/tests/Chemistry/transition-elements",
    },
  ];